// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfygydevhnjnpccowoxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeWd5ZGV2aG5qbnBjY293b3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODg0ODUsImV4cCI6MjA3Mzc2NDQ4NX0.z4tQvntSfvsbROFsrQJP3K-avujOBGr1XtaW8fjbj1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});